/**
 * Generates demo/qa-handoff-summary.md — a paste-ready QA handoff note for
 * GitHub PRs, Jira tickets, or Azure DevOps work items.
 *
 * Reads demo/changed-endpoints.json and the generated collection.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import {
  CHANGED_ENDPOINTS_PATH,
  COLLECTION_NAME,
  COLLECTION_PATH,
  ENVIRONMENT_NAME,
  REPO_ROOT
} from "./generate-postman-collection";

export const SUMMARY_PATH = path.join(REPO_ROOT, "demo", "qa-handoff-summary.md");

interface CollectionItem {
  name: string;
  item?: CollectionItem[];
}

function countRequests(items: CollectionItem[]): number {
  let count = 0;
  for (const item of items) {
    count += item.item ? countRequests(item.item) : 1;
  }
  return count;
}

export interface SummaryResult {
  summaryPath: string;
  requestCount: number;
}

export function generateQaHandoffSummary(collectionRunStatus?: string): SummaryResult {
  const changed = JSON.parse(fs.readFileSync(CHANGED_ENDPOINTS_PATH, "utf8"));
  if (!fs.existsSync(COLLECTION_PATH)) {
    throw new Error(
      `Collection not found at ${path.relative(REPO_ROOT, COLLECTION_PATH)}. Run 'npm run generate:collection' first.`
    );
  }
  const collection = JSON.parse(fs.readFileSync(COLLECTION_PATH, "utf8"));
  const requestCount = countRequests(collection.item);
  const folders: string[] = collection.item.map((f: CollectionItem) => f.name);

  const endpointRows = changed.endpoints
    .map(
      (e: any) =>
        `| \`${e.method} ${e.path.replace(/\{\{(\w+)\}\}/g, ":$1")}\` | ${e.change} | ${e.description ?? ""} |`
    )
    .join("\n");

  const runStatus =
    collectionRunStatus ??
    "_Not run yet — start the API (`npm run dev`) and run `npm run test:postman`, or run the collection in Postman._";

  const md = `# QA Handoff — ${changed.branch}

**Status: QA handoff ready** ✅

The Postman collection **"${COLLECTION_NAME}"** has been generated/updated for this branch and is ready to run. Import it (or open it in the QA workspace) and run it against a local API instance.

## New or changed endpoints

| Endpoint | Change | Notes |
| --- | --- | --- |
${endpointRows}

## Test coverage added

Every request carries QA's standard test policy (\`qa/postman/test-policy.json\`):

- **Response time** budget (&lt; 800 ms) on every request
- **Standard error shape** (\`{ error: { code, message } }\`) enforced on every request
- **Auth required** — missing-token negative request (401 \`UNAUTHORIZED\`) for each authenticated endpoint
- **Schema validation** — happy-path responses checked for all expected fields
- **Validation errors** — malformed-body negative requests (400 \`VALIDATION_ERROR\` with field details)
- **Unknown resources** — invalid project/submittal IDs return 403/404 with the standard error shape
- **Empty search results** — zero matches returns 200 with \`results: []\`, never 404
- **Create resource** — 201 with \`SUB-\` prefixed ID; ID saved as a collection variable for chained requests

Collection layout: ${folders.map((f) => `**${f}**`).join(" / ")} — **${requestCount} requests** total (happy path + negatives).

## Environment QA needs

Import \`postman/${ENVIRONMENT_NAME}.postman_environment.json\` (demo-only values, no secrets):

| Variable | Value |
| --- | --- |
| \`baseUrl\` | \`http://localhost:3000\` |
| \`authToken\` | \`demo-token\` |
| \`projectId\` | \`PRJ-1001\` |
| \`documentId\` | \`DOC-9001\` |
| \`submittalId\` | \`SUB-7001\` |

## Collection run status

${runStatus}

## How to run locally

\`\`\`bash
npm install
npm run dev            # terminal 1 — starts the API on :3000
npm run test:postman   # terminal 2 — the Postman CLI runs the collection with the local environment
\`\`\`

---
_Generated by \`npm run make:qa-ready\` from \`demo/changed-endpoints.json\` + QA test templates._
`;

  fs.writeFileSync(SUMMARY_PATH, md, "utf8");
  return { summaryPath: SUMMARY_PATH, requestCount };
}

if (require.main === module) {
  const result = generateQaHandoffSummary();
  console.log(`QA handoff summary written: ${path.relative(REPO_ROOT, result.summaryPath)}`);
}
